# Generated by Django 5.2.5 on 2025-08-20 11:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_student_id_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('school_id', 'School ID'), ('report_card', 'Report Card/Grades'), ('enrollment_certificate', 'Certificate of Enrollment'), ('barangay_clearance', 'Barangay Clearance'), ('parents_id', "Parent's Valid ID"), ('voter_certification', "Voter's Certification"), ('other', 'Other Document')], max_length=30)),
                ('document_file', models.FileField(upload_to='documents/%Y/%m/')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_needed', 'Revision Needed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Format: YYYY-YYYY (e.g., 2024-2025)', max_length=9)),
                ('semester', models.CharField(choices=[('1st', '1st Semester'), ('2nd', '2nd Semester'), ('summer', 'Summer')], max_length=10)),
                ('total_units', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('general_weighted_average', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(65.0), django.core.validators.MaxValueValidator(100.0)])),
                ('semestral_weighted_average', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(65.0), django.core.validators.MaxValueValidator(100.0)])),
                ('grade_sheet', models.FileField(upload_to='grades/%Y/%m/')),
                ('has_failing_grades', models.BooleanField(default=False)),
                ('has_incomplete_grades', models.BooleanField(default=False)),
                ('has_dropped_subjects', models.BooleanField(default=False)),
                ('ai_evaluation_completed', models.BooleanField(default=False)),
                ('ai_evaluation_notes', models.TextField(blank=True, null=True)),
                ('qualifies_for_basic_allowance', models.BooleanField(default=False)),
                ('qualifies_for_merit_incentive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_grades', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'academic_year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='AllowanceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('basic', 'Basic Educational Assistance (₱5,000)'), ('merit', 'Merit Incentive (₱5,000)'), ('both', 'Both Allowances (₱10,000)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grade_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gradesubmission')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'grade_submission')},
            },
        ),
    ]
