# Generated by Django 5.2.5 on 2025-08-21 05:00

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_documentsubmission_gradesubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.profile_image_upload_path),
        ),
    ]
