# Generated by Django 5.2.5 on 2025-09-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_scholarshipapplication_scholarshipdocument'),
        ('myapp', '0004_customuser_profile_image'),
    ]

    operations = [
    ]
