# Generated by Django 5.2.5 on 2025-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merge_20250903_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipdocument',
            name='application',
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='ai_analysis_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='ai_analysis_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='ai_auto_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='ai_confidence_score',
            field=models.FloatField(default=0.0, help_text='AI confidence score (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='ai_document_type_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='ai_extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='ai_key_information',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='ai_quality_assessment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='ai_recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gradesubmission',
            name='ai_confidence_score',
            field=models.FloatField(default=0.0, help_text='AI analysis confidence (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='gradesubmission',
            name='ai_extracted_grades',
            field=models.JSONField(blank=True, default=dict, help_text='AI extracted grade data'),
        ),
        migrations.AddField(
            model_name='gradesubmission',
            name='ai_grade_validation',
            field=models.JSONField(blank=True, default=dict, help_text='AI grade validation results'),
        ),
        migrations.AddField(
            model_name='gradesubmission',
            name='ai_recommendations',
            field=models.JSONField(blank=True, default=list, help_text='AI recommendations'),
        ),
        migrations.AlterField(
            model_name='documentsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_needed', 'Revision Needed'), ('ai_processing', 'AI Processing')], default='pending', max_length=20),
        ),
            # Removed DeleteModel for ScholarshipApplication and ScholarshipDocument (models no longer exist)
    ]
