# Generated by Django 5.2.5 on 2025-09-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_merge_20250903_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipdocument',
            name='application',
        ),
        migrations.DeleteModel(
            name='ScholarshipApplication',
        ),
        migrations.DeleteModel(
            name='ScholarshipDocument',
        ),
    ]
