# Generated by Django 5.2.5 on 2025-09-22 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ai_integration_fields'),
    ]

    operations = [
    ]
