# Generated by Django 5.2.5 on 2025-10-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_documentsubmission_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsubmission',
            name='document_type',
            field=models.CharField(choices=[('academic_records', 'Academic Records (Grade 10/12 Report Card, Certificate, or Diploma)'), ('valid_id', 'Valid ID (School ID, Birth Certificate, or Government-issued ID)'), ('certificate_of_enrollment', 'Certificate of Enrollment'), ('junior_hs_certificate', 'Junior High School Certificate/Grade 10 Report Card/Certification from Principal'), ('senior_hs_diploma', 'Senior High School Diploma/Grade 12 Report Card/Certification from Principal'), ('school_id', 'School ID or Valid Government-issued ID'), ('birth_certificate', 'Birth Certificate (issued by PSA/NSO/Civil Registry Office)'), ('form_137', 'Certified True Copy of Elementary and/or High School Form 137'), ('als_certificate', 'ALS Certificate (if ALS Graduate)'), ('death_certificate', 'Death Certificate (Parents, if claimed to be deceased, issued by PSA/NSO/Civil Registry Office)'), ('work_contract_visa', 'Work Contract/VISA/Passport (if any of both parents are OFWs)'), ('comelec_stub', 'Original copy and one (1) photocopy of Comelec Stub (issued after May 2022 Elections)'), ('umid_card', 'UMID Card'), ('drivers_license', "Driver's License"), ('passport', 'Passport'), ('sss_id', 'SSS ID'), ('voters_id', "Voter's ID"), ('bir_tin_id', 'BIR (TIN) ID'), ('pag_ibig_id', 'Pag-IBIG ID'), ('company_id', 'Company ID'), ('postal_id', 'Postal ID'), ('philhealth_id', 'PhilHealth ID'), ('philsys_id', 'Philippine Identification (PhilID/PhilSys) National ID'), ('afp_beneficiary_id', "AFP Beneficiary/Dependent's ID"), ('report_card', 'Report Card/Grades'), ('enrollment_certificate', 'Certificate of Enrollment'), ('barangay_clearance', 'Barangay Clearance'), ('parents_id', "Parent's Valid ID"), ('voter_certification', "Voter's Certification"), ('other', 'Other Document')], max_length=30),
        ),
    ]
