# Generated by Django 5.2.5 on 2025-10-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_documentsubmission_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowanceapplication',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Completion email sent'),
        ),
        migrations.AddField(
            model_name='allowanceapplication',
            name='schedule_date',
            field=models.DateTimeField(blank=True, help_text='Expected date for application response', null=True),
        ),
        migrations.AddField(
            model_name='allowanceapplication',
            name='status_email_sent',
            field=models.BooleanField(default=False, help_text='Status update email sent'),
        ),
    ]
