# Generated by Django 5.2.5 on 2025-10-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_allowanceapplication_email_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowanceapplication',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='allowanceapplication',
            name='status_email_sent',
        ),
        migrations.AddField(
            model_name='allowanceapplication',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allowanceapplication',
            name='notification_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='allowanceapplication',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
