# Generated by Django 5.2.5 on 2025-10-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_allowanceapplication_schedule_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='middle_initial',
            field=models.CharField(blank=True, help_text='Middle initial (e.g., A. or M.)', max_length=5, null=True),
        ),
    ]
