# Generated by Django 5.2.5 on 2025-10-07 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_customuser_middle_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('total_admins', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('active_users_today', models.IntegerField(default=0)),
                ('total_documents', models.IntegerField(default=0)),
                ('documents_pending', models.IntegerField(default=0)),
                ('documents_approved', models.IntegerField(default=0)),
                ('documents_rejected', models.IntegerField(default=0)),
                ('documents_submitted_today', models.IntegerField(default=0)),
                ('total_grades', models.IntegerField(default=0)),
                ('grades_pending', models.IntegerField(default=0)),
                ('grades_approved', models.IntegerField(default=0)),
                ('grades_rejected', models.IntegerField(default=0)),
                ('grades_submitted_today', models.IntegerField(default=0)),
                ('total_applications', models.IntegerField(default=0)),
                ('applications_pending', models.IntegerField(default=0)),
                ('applications_approved', models.IntegerField(default=0)),
                ('applications_rejected', models.IntegerField(default=0)),
                ('applications_disbursed', models.IntegerField(default=0)),
                ('applications_submitted_today', models.IntegerField(default=0)),
                ('total_amount_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ai_analyses_completed', models.IntegerField(default=0)),
                ('ai_auto_approvals', models.IntegerField(default=0)),
                ('avg_ai_confidence_score', models.FloatField(default=0.0)),
                ('avg_document_processing_time', models.FloatField(default=0.0, help_text='Average time in hours')),
                ('avg_grade_processing_time', models.FloatField(default=0.0, help_text='Average time in hours')),
                ('avg_application_processing_time', models.FloatField(default=0.0, help_text='Average time in hours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='documentsubmission',
            name='document_type',
            field=models.CharField(choices=[('academic_records', 'Academic Records (Grade 10/12 Report Card, Certificate, or Diploma)'), ('valid_id', 'Valid ID (School ID, Birth Certificate, or Government-issued ID)'), ('certificate_of_enrollment', 'Certificate of Enrollment'), ('transcript_of_records', 'Transcript of Records'), ('junior_hs_certificate', 'Junior High School Certificate/Grade 10 Report Card/Certification from Principal'), ('senior_hs_diploma', 'Senior High School Diploma/Grade 12 Report Card/Certification from Principal'), ('school_id', 'School ID or Valid Government-issued ID'), ('birth_certificate', 'Birth Certificate (issued by PSA/NSO/Civil Registry Office)'), ('grade_10_report_card', 'Grade 10 Report Card'), ('grade_12_report_card', 'Grade 12 Report Card'), ('diploma', 'Diploma'), ('form_137', 'Certified True Copy of Elementary and/or High School Form 137'), ('als_certificate', 'ALS Certificate (if ALS Graduate)'), ('death_certificate', 'Death Certificate (Parents, if claimed to be deceased, issued by PSA/NSO/Civil Registry Office)'), ('work_contract_visa', 'Work Contract/VISA/Passport (if any of both parents are OFWs)'), ('comelec_stub', 'Original copy and one (1) photocopy of Comelec Stub (issued after May 2022 Elections)'), ('umid_card', 'UMID Card'), ('drivers_license', "Driver's License"), ('passport', 'Passport'), ('sss_id', 'SSS ID'), ('voters_id', "Voter's ID"), ('bir_tin_id', 'BIR (TIN) ID'), ('pag_ibig_id', 'Pag-IBIG ID'), ('company_id', 'Company ID'), ('postal_id', 'Postal ID'), ('philhealth_id', 'PhilHealth ID'), ('philsys_id', 'Philippine Identification (PhilID/PhilSys) National ID'), ('afp_beneficiary_id', "AFP Beneficiary/Dependent's ID"), ('report_card', 'Report Card/Grades'), ('enrollment_certificate', 'Certificate of Enrollment'), ('barangay_clearance', 'Barangay Clearance'), ('parents_id', "Parent's Valid ID"), ('voter_certification', "Voter's Certification"), ('other', 'Other Document'), ('others', 'Others')], max_length=30),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('document_submitted', 'Document Submitted'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('document_revised', 'Document Revision Requested'), ('grade_submitted', 'Grade Submitted'), ('grade_approved', 'Grade Approved'), ('grade_rejected', 'Grade Rejected'), ('grade_processed', 'Grade Processed'), ('application_submitted', 'Application Submitted'), ('application_approved', 'Application Approved'), ('application_rejected', 'Application Rejected'), ('application_disbursed', 'Application Disbursed'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_registered', 'User Registered'), ('user_updated', 'User Profile Updated'), ('password_changed', 'Password Changed'), ('admin_review', 'Admin Review Performed'), ('admin_action', 'Admin Action Taken'), ('system_config', 'System Configuration Changed'), ('ai_analysis', 'AI Analysis Completed'), ('ai_auto_approve', 'AI Auto-Approval'), ('other', 'Other Action')], max_length=30)),
                ('action_description', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('success', 'Success')], default='info', max_length=10)),
                ('target_model', models.CharField(blank=True, help_text='Model name (e.g., DocumentSubmission)', max_length=50, null=True)),
                ('target_object_id', models.IntegerField(blank=True, help_text='ID of the affected object', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional action metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by the action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='myapp_audit_timesta_1d0701_idx'), models.Index(fields=['user', '-timestamp'], name='myapp_audit_user_id_0c1de2_idx'), models.Index(fields=['action_type', '-timestamp'], name='myapp_audit_action__125fea_idx'), models.Index(fields=['severity', '-timestamp'], name='myapp_audit_severit_086c2b_idx')],
            },
        ),
    ]
