# Generated by Django 5.2.5 on 2025-10-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_gradesubmission_general_weighted_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ai_verification_score',
            field=models.FloatField(default=0.0, help_text='AI verification confidence score (0.0-1.0)'),
        ),
    ]
