# Generated by Django 5.2.5 on 2025-10-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_customuser_ai_verification_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsubmission',
            name='address_match_score',
            field=models.FloatField(default=0.0, help_text='Address matching confidence score (0.0-1.0)'),
        ),
    ]
