# Generated by Django 5.2.5 on 2025-11-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_customuser_is_email_verified_and_more'),
        ('myapp', '0016_documentsubmission_address_match_score'),
    ]

    operations = [
    ]
