# Generated by Django 5.1.13 on 2025-10-29 11:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_documentsubmission_address_match_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, help_text='Format: YY-XXXXX (e.g., 22-00001)', max_length=20, unique=True)),
                ('first_name', models.CharField(db_index=True, help_text="Student's legal first name", max_length=100)),
                ('last_name', models.CharField(db_index=True, help_text="Student's legal last name", max_length=100)),
                ('middle_initial', models.CharField(blank=True, help_text="Middle initial or 'N/A' if none", max_length=10, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('course', models.CharField(choices=[('BSCS', 'Bachelor of Science in Computer Science'), ('BSIT', 'Bachelor of Science in Information Technology'), ('BSIS', 'Bachelor of Science in Information Systems')], max_length=10)),
                ('year_level', models.IntegerField(help_text='Current year level (1-6)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('is_active', models.BooleanField(default=True, help_text='Can this student register?')),
                ('has_registered', models.BooleanField(default=False, help_text='Has this student completed registration?')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this student', null=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Admin who added this verified student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_students_added', to=settings.AUTH_USER_MODEL)),
                ('registered_user', models.ForeignKey(blank=True, help_text='Linked user account after registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_student_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verified Student',
                'verbose_name_plural': 'Verified Students',
                'ordering': ['student_id'],
                'indexes': [models.Index(fields=['student_id', 'is_active'], name='myapp_verif_student_d1c9e8_idx'), models.Index(fields=['last_name', 'first_name'], name='myapp_verif_last_na_2302fb_idx')],
            },
        ),
    ]
