# Generated by Django 5.2.5 on 2025-11-03 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_merge_20251102_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enrolled', models.BooleanField(default=False, help_text='Currently enrolled at Taguig City University')),
                ('is_resident', models.BooleanField(default=False, help_text='Bona fide resident of Taguig City for at least 3 years')),
                ('is_eighteen_or_older', models.BooleanField(default=False, help_text='18 years old or older')),
                ('is_registered_voter', models.BooleanField(default=False, help_text='Registered voter of the City')),
                ('parent_is_voter', models.BooleanField(default=False, help_text='One parent is an active voter of Taguig City')),
                ('has_good_moral_character', models.BooleanField(default=False, help_text='Possesses good moral character')),
                ('is_committed', models.BooleanField(default=False, help_text='Committed to love and serve Taguig City')),
                ('applicant_type', models.CharField(choices=[('new', 'New Applicant'), ('renewing', 'Renewing Applicant')], default='new', max_length=10)),
                ('is_qualified', models.BooleanField(default=False, help_text='Automatically set to True if all criteria are met')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='basic_qualification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Basic Qualification',
                'verbose_name_plural': 'Basic Qualifications',
                'ordering': ['-completed_at'],
            },
        ),
    ]
