# Generated by Django 5.1.13 on 2025-10-30 00:57

import myapp.models
import myapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_add_verified_student_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.profile_image_upload_path, validators=[myapp.validators.FileSizeValidator(max_size_mb=5, min_size_kb=1), myapp.validators.FileTypeValidator(allowed_category='image'), myapp.validators.ProfileImageValidator(max_size_mb=5), myapp.validators.MaliciousFileValidator()]),
        ),
        migrations.AlterField(
            model_name='documentsubmission',
            name='document_file',
            field=models.FileField(upload_to='documents/%Y/%m/', validators=[myapp.validators.FileSizeValidator(max_size_mb=10, min_size_kb=1), myapp.validators.FileTypeValidator(allowed_category='document'), myapp.validators.MaliciousFileValidator()]),
        ),
        migrations.AlterField(
            model_name='gradesubmission',
            name='grade_sheet',
            field=models.FileField(upload_to='grades/%Y/%m/', validators=[myapp.validators.FileSizeValidator(max_size_mb=10, min_size_kb=1), myapp.validators.FileTypeValidator(allowed_category='grade_sheet'), myapp.validators.MaliciousFileValidator()]),
        ),
    ]
