# Generated by Django 5.2.5 on 2025-11-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_basicqualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicqualification',
            name='has_good_moral_character',
            field=models.BooleanField(blank=True, default=False, help_text='Possesses good moral character', null=True),
        ),
        migrations.AlterField(
            model_name='basicqualification',
            name='is_committed',
            field=models.BooleanField(blank=True, default=False, help_text='Committed to love and serve Taguig City', null=True),
        ),
        migrations.AlterField(
            model_name='basicqualification',
            name='is_eighteen_or_older',
            field=models.BooleanField(blank=True, default=False, help_text='18 years old or older', null=True),
        ),
        migrations.AlterField(
            model_name='basicqualification',
            name='is_enrolled',
            field=models.BooleanField(blank=True, default=False, help_text='Currently enrolled at Taguig City University', null=True),
        ),
        migrations.AlterField(
            model_name='basicqualification',
            name='is_registered_voter',
            field=models.BooleanField(blank=True, default=False, help_text='Registered voter of the City', null=True),
        ),
        migrations.AlterField(
            model_name='basicqualification',
            name='is_resident',
            field=models.BooleanField(blank=True, default=False, help_text='Bona fide resident of Taguig City for at least 3 years', null=True),
        ),
        migrations.AlterField(
            model_name='basicqualification',
            name='parent_is_voter',
            field=models.BooleanField(blank=True, default=False, help_text='One parent is an active voter of Taguig City', null=True),
        ),
    ]
