# Generated by Django 5.1.13 on 2025-11-03 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0018_add_file_validators"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True, help_text="When email was verified", null=True
            ),
        ),
        # Note: is_email_verified field already added in 0014_customuser_is_email_verified_and_more.py
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="6-digit verification code", max_length=6
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this code expires"),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has this code been successfully verified",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When this code was verified", null=True
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Has this code been used (prevents reuse)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "code", "is_used"],
                        name="myapp_email_user_id_8fae57_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="myapp_email_expires_d0ab80_idx"
                    ),
                ],
            },
        ),
    ]
