# Generated by Django 5.2.5 on 2025-11-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_add_file_validators'),
        ('myapp', '0019_alter_basicqualification_has_good_moral_character_and_more'),
    ]

    operations = [
    ]
