# Generated by Django 5.2.5 on 2025-11-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_customuser_email_verified_at_and_more'),
        ('myapp', '0020_merge_20251104_2222'),
    ]

    operations = [
    ]
