# Generated by Django 5.2.5 on 2025-11-05 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_merge_20251105_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(help_text='School year (e.g., 2024-2025)', max_length=20)),
                ('semester', models.CharField(choices=[('1st', 'First Semester'), ('2nd', 'Second Semester'), ('summer', 'Summer')], default='1st', max_length=10)),
                ('application_type', models.CharField(choices=[('new', 'New Application'), ('renewal', 'Renewal')], default='new', max_length=10)),
                ('email', models.EmailField(help_text="Student's email address", max_length=254)),
                ('contact_number', models.CharField(help_text='Contact number', max_length=15)),
                ('birth_date', models.DateField(help_text='Date of birth')),
                ('barangay', models.CharField(help_text='Barangay of residence', max_length=100)),
                ('is_submitted', models.BooleanField(default=False, help_text='Whether the application has been submitted')),
                ('is_locked', models.BooleanField(default=False, help_text='Whether the application is locked for editing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When the application was submitted', null=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='full_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Full Application',
                'verbose_name_plural': 'Full Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
