# Generated by Django 5.2.5 on 2025-11-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_fullapplication_delete_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullapplication',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='fullapplication',
            name='contact_number',
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='applying_for_merit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='citizenship',
            field=models.CharField(default='Filipino', max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='course_duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='course_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='district',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='elem_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='elem_attended',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='elem_honors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='elem_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='elem_years',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='father_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='father_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='father_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='father_education',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='father_place_of_work',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='graduating_this_term',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='house_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='jhs_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='jhs_attended',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='jhs_honors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='jhs_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='jhs_years',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='ladderized',
            field=models.CharField(default='NO', max_length=10),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='marital_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='mobile_no',
            field=models.CharField(default='', help_text='Contact number', max_length=15),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='mother_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='mother_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='mother_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='mother_education',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='mother_place_of_work',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='other_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='place_of_birth',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='religion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='scholarship_type',
            field=models.CharField(default='TCU-CEAA', max_length=100),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='school_address',
            field=models.CharField(default='Gen. Santos Ave., Central Bicutan, Taguig City', max_length=500),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='school_name',
            field=models.CharField(default='TAGUIG CITY UNIVERSITY (TCU)', max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='semesters_to_graduate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='shiftee',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='shs_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='shs_attended',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='shs_honors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='shs_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='shs_years',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='street',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='swa_input',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='transferee',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='units_enrolled',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='with_honors',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='year_level',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='years_of_residency',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fullapplication',
            name='zip_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='fullapplication',
            name='barangay',
            field=models.CharField(default='', help_text='Barangay of residence', max_length=100),
        ),
        migrations.AlterField(
            model_name='fullapplication',
            name='email',
            field=models.EmailField(default='', help_text="Student's email address", max_length=254),
        ),
    ]
