# Generated by Django 5.2.5 on 2025-11-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_fullapplication_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Email address has been verified'),
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
