# Generated by Django 5.1.13 on 2025-11-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_alter_customuser_is_email_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsubmission",
            name="face_detected_in_document",
            field=models.BooleanField(
                default=False, help_text="Whether a face was detected in the document"
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="face_embedding",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Face embedding vector for comparison",
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="face_match_confidence",
            field=models.CharField(
                blank=True,
                help_text="Confidence level: very_low, low, medium, high, very_high",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="face_match_score",
            field=models.FloatField(
                default=0.0, help_text="Face similarity score (0.0-1.0)"
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="face_verification_completed",
            field=models.BooleanField(
                default=False,
                help_text="Whether face verification with selfie was done",
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="liveness_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Liveness challenge results (color flash, blink, movement)",
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="liveness_verification_completed",
            field=models.BooleanField(
                default=False, help_text="Whether liveness verification was performed"
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="liveness_verification_passed",
            field=models.BooleanField(
                default=False, help_text="Whether liveness checks passed"
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="selfie_captured",
            field=models.BooleanField(
                default=False,
                help_text="Whether a live selfie was captured for verification",
            ),
        ),
        migrations.AddField(
            model_name="gradesubmission",
            name="ai_grades_confidence",
            field=models.FloatField(
                default=0.0, help_text="Confidence in OCR grade detection (0.0-1.0)"
            ),
        ),
        migrations.AddField(
            model_name="gradesubmission",
            name="ai_grades_detected",
            field=models.BooleanField(
                default=False, help_text="Whether AI detected grades from document"
            ),
        ),
        migrations.AddField(
            model_name="gradesubmission",
            name="ai_grades_recommendations",
            field=models.JSONField(
                blank=True, default=list, help_text="Merit-based recommendations"
            ),
        ),
        migrations.AddField(
            model_name="gradesubmission",
            name="ai_gwa_calculated",
            field=models.FloatField(
                blank=True, help_text="AI-calculated GWA from OCR", null=True
            ),
        ),
        migrations.AddField(
            model_name="gradesubmission",
            name="ai_merit_level",
            field=models.CharField(
                blank=True,
                help_text="AI-determined merit level",
                max_length=50,
                null=True,
            ),
        ),
    ]
