# Generated by Django 5.1.13 on 2025-11-14 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0025_documentsubmission_face_detected_in_document_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_id",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "fraud_type",
                    models.CharField(
                        choices=[
                            ("face_mismatch", "Face Verification Failed"),
                            ("liveness_failed", "Liveness Detection Failed"),
                            ("stolen_identity", "Suspected Stolen Identity"),
                            ("document_tampering", "Document Tampering Detected"),
                            (
                                "multiple_attempts",
                                "Multiple Failed Verification Attempts",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Investigation"),
                            ("investigating", "Under Investigation"),
                            ("confirmed_fraud", "Confirmed Fraud"),
                            ("resolved", "Resolved - Real Owner Verified"),
                            ("dismissed", "Dismissed - False Positive"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical - Immediate Action Required"),
                        ],
                        default="high",
                        max_length=10,
                    ),
                ),
                (
                    "face_match_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Face similarity score (0.0-1.0) from failed verification",
                    ),
                ),
                (
                    "liveness_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Liveness verification data from failed attempt",
                    ),
                ),
                (
                    "verification_attempts",
                    models.IntegerField(
                        default=1,
                        help_text="Number of verification attempts before flagging as fraud",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the fraud attempt"
                    ),
                ),
                (
                    "evidence_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional evidence (timestamps, IP addresses, device info, etc.)",
                    ),
                ),
                (
                    "suspected_real_identity",
                    models.TextField(
                        blank=True,
                        help_text="Details of the real identity owner if discovered",
                        null=True,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin investigation notes", null=True
                    ),
                ),
                (
                    "actions_taken",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of actions taken (account suspension, notification sent, etc.)",
                    ),
                ),
                (
                    "real_owner_contacted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the real identity owner has been contacted",
                    ),
                ),
                (
                    "real_owner_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the real owner has been verified and guided",
                    ),
                ),
                (
                    "real_owner_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about real owner contact and verification",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "allowance_application",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related allowance application if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_reports",
                        to="myapp.allowanceapplication",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related full application if applicable",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_reports",
                        to="myapp.fullapplication",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_fraud_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="Document that failed verification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_reports",
                        to="myapp.documentsubmission",
                    ),
                ),
                (
                    "suspected_user",
                    models.ForeignKey(
                        help_text="User account that attempted fraud",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_reports_as_suspect",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FraudNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("new_fraud_report", "New Fraud Report"),
                            ("high_severity_alert", "High Severity Alert"),
                            ("multiple_attempts", "Multiple Failed Attempts"),
                            ("real_owner_contacted", "Real Owner Contacted"),
                            ("fraud_resolved", "Fraud Case Resolved"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="high",
                        max_length=10,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        limit_choices_to={"role": "admin"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fraud_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fraud_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="myapp.fraudreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAccountAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("suspended", "Account Suspended"),
                            ("flagged", "Account Flagged"),
                            ("investigation", "Under Investigation"),
                            ("reinstated", "Account Reinstated"),
                            ("permanently_banned", "Permanently Banned"),
                        ],
                        max_length=30,
                    ),
                ),
                ("reason", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When temporary suspension expires",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fraud_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_actions",
                        to="myapp.fraudreport",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_account_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="fraudreport",
            index=models.Index(
                fields=["status", "severity"], name="myapp_fraud_status_4e3e90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fraudreport",
            index=models.Index(
                fields=["suspected_user", "status"],
                name="myapp_fraud_suspect_b86905_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fraudreport",
            index=models.Index(
                fields=["created_at"], name="myapp_fraud_created_5c6592_idx"
            ),
        ),
    ]
