# Generated by Django 5.1.13 on 2025-11-16 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0026_fraudreport_fraudnotification_useraccountaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsubmission",
            name="extracted_subjects",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of subjects extracted from COE: [{subject_code, subject_name}, ...]",
            ),
        ),
        migrations.AddField(
            model_name="documentsubmission",
            name="subject_count",
            field=models.IntegerField(
                default=0, help_text="Total number of subjects extracted from COE"
            ),
        ),
        migrations.AddField(
            model_name="gradesubmission",
            name="grade_received",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Grade for this subject",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gradesubmission",
            name="subject_code",
            field=models.CharField(
                blank=True,
                help_text="Subject code (e.g., GE101, MATH101)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gradesubmission",
            name="subject_name",
            field=models.CharField(
                blank=True,
                help_text="Subject name (e.g., Technopreneurship)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gradesubmission",
            name="units",
            field=models.IntegerField(
                blank=True,
                help_text="Number of units for this subject",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="gradesubmission",
            name="general_weighted_average",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="gradesubmission",
            name="total_units",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
    ]
