# Generated by Django 5.2.5 on 2025-11-17 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0027_add_subject_tracking_fields"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gradesubmission",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="gradesubmission",
            name="academic_year",
            field=models.CharField(
                help_text="Format: YYYY-YYYY (e.g., 2024-2025)", max_length=20
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gradesubmission",
            unique_together={("student", "academic_year", "semester", "subject_code")},
        ),
    ]
