# Generated by Django 5.1.13 on 2025-11-18 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0028_alter_gradesubmission_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowanceapplication",
            name="face_verification_attempted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When face verification was last attempted",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allowanceapplication",
            name="face_verification_completed",
            field=models.BooleanField(
                default=False, help_text="Whether face verification has been completed"
            ),
        ),
        migrations.AddField(
            model_name="allowanceapplication",
            name="face_verification_confidence",
            field=models.CharField(
                blank=True,
                help_text="Face verification confidence level",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allowanceapplication",
            name="face_verification_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Detailed face verification results"
            ),
        ),
        migrations.AddField(
            model_name="allowanceapplication",
            name="face_verification_notes",
            field=models.TextField(
                blank=True, help_text="Notes from face verification process", null=True
            ),
        ),
        migrations.AddField(
            model_name="allowanceapplication",
            name="face_verification_passed",
            field=models.BooleanField(
                blank=True, help_text="Whether face verification passed", null=True
            ),
        ),
        migrations.AddField(
            model_name="allowanceapplication",
            name="face_verification_required",
            field=models.BooleanField(
                default=True,
                help_text="Whether face verification is required for this application",
            ),
        ),
        migrations.AddField(
            model_name="allowanceapplication",
            name="face_verification_score",
            field=models.FloatField(
                blank=True,
                help_text="Face verification similarity score (0.0-1.0)",
                null=True,
            ),
        ),
    ]
