# Generated by Django 5.2.5 on 2025-11-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0029_add_face_verification_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowanceapplication",
            name="last_verification_attempt_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of last verification attempt",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allowanceapplication",
            name="verification_attempt_count",
            field=models.IntegerField(
                default=0, help_text="Number of failed verification attempts"
            ),
        ),
        migrations.AddField(
            model_name="allowanceapplication",
            name="verification_cooldown_until",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user can try verification again (after 3 failed attempts, cooldown 24 hours)",
                null=True,
            ),
        ),
    ]
