# Generated by Django 5.2.5 on 2025-11-18 19:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0030_allowanceapplication_last_verification_attempt_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationAdjudication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "school_id_image_path",
                    models.CharField(
                        help_text="Path to School ID image", max_length=500
                    ),
                ),
                (
                    "selfie_image_path",
                    models.CharField(
                        help_text="Path to live selfie/face capture image",
                        max_length=500,
                    ),
                ),
                (
                    "automated_rekognition_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Automated face similarity score (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "automated_match_result",
                    models.BooleanField(
                        default=False, help_text="Automated service match decision"
                    ),
                ),
                (
                    "verification_backend",
                    models.CharField(
                        choices=[
                            ("rekognition_masked", "AWS Rekognition (Masked)"),
                            ("yolo_insightface", "YOLO/InsightFace"),
                        ],
                        default="yolo_insightface",
                        help_text="Which verification backend was used",
                        max_length=20,
                    ),
                ),
                (
                    "automated_verification_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complete automated verification response",
                    ),
                ),
                (
                    "admin_decision",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Admin Review"),
                            ("approved", "Approved by Admin"),
                            ("rejected", "Rejected by Admin"),
                            ("escalated", "Escalated for Investigation"),
                        ],
                        default="pending",
                        help_text="Admin final decision on identity verification",
                        max_length=20,
                    ),
                ),
                (
                    "admin_decision_score",
                    models.FloatField(
                        blank=True,
                        help_text="Admin confidence score (optional override)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, help_text="Admin review notes and reasoning"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_review", "Pending Admin Review"),
                            ("under_review", "Under Admin Review"),
                            ("completed", "Review Completed"),
                            ("error", "Processing Error"),
                        ],
                        default="pending_review",
                        help_text="Current processing status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When verification request was created",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When admin completed review", null=True
                    ),
                ),
                (
                    "admin_device_info",
                    models.CharField(
                        blank=True,
                        help_text="Device info of admin reviewer",
                        max_length=255,
                    ),
                ),
                (
                    "admin_ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address of admin reviewer", null=True
                    ),
                ),
                (
                    "admin_reviewer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who reviewed this adjudication",
                        limit_choices_to={"role": "admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="face_adjudications_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        help_text="Allowance application (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_adjudications",
                        to="myapp.allowanceapplication",
                    ),
                ),
                (
                    "document_submission",
                    models.ForeignKey(
                        blank=True,
                        help_text="Document submission (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_adjudications",
                        to="myapp.documentsubmission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User undergoing verification",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_adjudications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Verification Adjudication",
                "verbose_name_plural": "Face Verification Adjudications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="myapp_verif_user_id_2c9823_idx",
                    ),
                    models.Index(
                        fields=["admin_decision", "-created_at"],
                        name="myapp_verif_admin_d_46d1c0_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="myapp_verif_status_614650_idx",
                    ),
                    models.Index(
                        fields=["application", "-created_at"],
                        name="myapp_verif_applica_da22b4_idx",
                    ),
                ],
            },
        ),
    ]
