# Generated by Django 5.2.5 on 2025-11-18 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0031_verificationadjudication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verificationadjudication",
            name="automated_rekognition_score",
        ),
        migrations.AddField(
            model_name="verificationadjudication",
            name="automated_confidence_level",
            field=models.CharField(
                choices=[
                    ("very_high", "Very High (≥99%)"),
                    ("high", "High (≥95%)"),
                    ("medium", "Medium (≥90%)"),
                    ("low", "Low (≥85%)"),
                    ("very_low", "Very Low (<85%)"),
                ],
                default="very_low",
                help_text="Automated verification confidence level",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="verificationadjudication",
            name="automated_liveness_score",
            field=models.FloatField(
                default=0.0,
                help_text="Liveness detection score (0.0-1.0, higher = more confident)",
            ),
        ),
        migrations.AddField(
            model_name="verificationadjudication",
            name="automated_similarity_score",
            field=models.FloatField(
                blank=True,
                help_text="Face similarity score (0.0-1.0, >0.99 = very high confidence)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="verificationadjudication",
            name="liveness_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Liveness detection challenge results",
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="admin_decision",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("escalated", "Escalated for Investigation"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="admin_decision_score",
            field=models.FloatField(
                blank=True,
                help_text="Optional admin override confidence score",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="admin_device_info",
            field=models.CharField(
                blank=True,
                help_text="Device info of admin reviewer",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Admin notes/comments on the verification",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="admin_reviewer",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who reviewed this verification",
                limit_choices_to={"role": "admin"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="face_verifications_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="face_verifications",
                to="myapp.allowanceapplication",
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="automated_match_result",
            field=models.BooleanField(
                default=False, help_text="Whether automated verification passed"
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="automated_verification_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Detailed automated verification results",
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="document_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="face_verifications",
                to="myapp.documentsubmission",
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, help_text="When admin completed the review", null=True
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="school_id_image_path",
            field=models.CharField(
                help_text="Path to the submitted School ID image", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="selfie_image_path",
            field=models.CharField(
                help_text="Path to the live captured selfie", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_review", "Pending Admin Review"),
                    ("under_review", "Currently Under Review"),
                    ("completed", "Review Completed"),
                    ("error", "Processing Error"),
                ],
                db_index=True,
                default="pending_review",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="face_verifications",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="verificationadjudication",
            name="verification_backend",
            field=models.CharField(
                choices=[
                    ("rekognition", "AWS Rekognition"),
                    ("yolo_insightface", "YOLO + InsightFace"),
                ],
                default="yolo_insightface",
                max_length=20,
            ),
        ),
    ]
