# Generated by Django 5.2.5 on 2025-11-23 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "myapp",
            "0032_remove_verificationadjudication_automated_rekognition_score_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FaceVerificationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="AWS Rekognition session ID or UUID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Session Created"),
                            ("in_progress", "Verification In Progress"),
                            ("completed", "Verification Completed"),
                            ("failed", "Verification Failed"),
                            ("expired", "Session Expired"),
                            ("fraud_detected", "Fraud Detected"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "verification_type",
                    models.CharField(
                        default="liveness_and_match",
                        help_text="Type of verification (liveness_only, face_match_only, liveness_and_match)",
                        max_length=50,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Overall verification confidence (0.0-100.0)",
                        null=True,
                    ),
                ),
                (
                    "liveness_score",
                    models.FloatField(
                        blank=True,
                        help_text="Liveness detection score (0.0-100.0)",
                        null=True,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        blank=True,
                        help_text="Face similarity score (0.0-100.0)",
                        null=True,
                    ),
                ),
                (
                    "is_live",
                    models.BooleanField(
                        default=False, help_text="Liveness check passed"
                    ),
                ),
                (
                    "face_match",
                    models.BooleanField(
                        default=False, help_text="Face matching passed"
                    ),
                ),
                (
                    "fraud_risk_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Fraud risk score (0.0-100.0, higher = more suspicious)",
                    ),
                ),
                (
                    "fraud_flags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of fraud detection flags",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Unique device identifier",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="User's IP address"),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Browser user agent string", null=True
                    ),
                ),
                (
                    "geolocation_country",
                    models.CharField(
                        blank=True,
                        help_text="Country from IP geolocation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "geolocation_region",
                    models.CharField(
                        blank=True,
                        help_text="Region/State from IP",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "geolocation_city",
                    models.CharField(
                        blank=True, help_text="City from IP", max_length=100, null=True
                    ),
                ),
                (
                    "is_vpn",
                    models.BooleanField(default=False, help_text="VPN/Proxy detected"),
                ),
                (
                    "is_philippines",
                    models.BooleanField(
                        default=False, help_text="IP originates from Philippines"
                    ),
                ),
                (
                    "attempt_number",
                    models.IntegerField(
                        default=1, help_text="Attempt number for this session"
                    ),
                ),
                (
                    "daily_attempt_count",
                    models.IntegerField(
                        default=0, help_text="Total attempts by user today"
                    ),
                ),
                (
                    "audit_image_url",
                    models.URLField(
                        blank=True, help_text="S3 URL to audit images", null=True
                    ),
                ),
                (
                    "reference_image_url",
                    models.URLField(
                        blank=True, help_text="S3 URL to reference image", null=True
                    ),
                ),
                (
                    "aws_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full AWS Rekognition API response",
                    ),
                ),
                (
                    "verification_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional verification metadata",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Session expiration time (5 minutes from creation)"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When verification completed", null=True
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated allowance application",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="face_verification_sessions",
                        to="myapp.allowanceapplication",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_verification_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Verification Session",
                "verbose_name_plural": "Face Verification Sessions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="myapp_facev_user_id_427f45_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="myapp_facev_status_41e285_idx",
                    ),
                    models.Index(
                        fields=["device_fingerprint", "-created_at"],
                        name="myapp_facev_device__426e82_idx",
                    ),
                    models.Index(
                        fields=["session_id", "status"],
                        name="myapp_facev_session_25e147_idx",
                    ),
                ],
            },
        ),
    ]
