# Generated by Django 5.2.5 on 2025-11-24 02:06

import myapp.models
import myapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0033_add_face_verification_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentsubmission",
            name="document_file",
            field=models.FileField(
                upload_to=myapp.models.document_upload_path,
                validators=[
                    myapp.validators.FileSizeValidator(max_size_mb=10, min_size_kb=1),
                    myapp.validators.FileTypeValidator(allowed_category="document"),
                    myapp.validators.MaliciousFileValidator(),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="gradesubmission",
            name="grade_sheet",
            field=models.FileField(
                upload_to=myapp.models.grade_upload_path,
                validators=[
                    myapp.validators.FileSizeValidator(max_size_mb=10, min_size_kb=1),
                    myapp.validators.FileTypeValidator(allowed_category="grade_sheet"),
                    myapp.validators.MaliciousFileValidator(),
                ],
            ),
        ),
    ]
