# Generated by Django 5.2.5 on 2025-11-28 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0035_documentsubmission_is_active"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.AddField(
            model_name="customuser",
            name="archive_reason",
            field=models.TextField(
                blank=True, help_text="Reason for archiving the user", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="archived_at",
            field=models.DateTimeField(
                blank=True, help_text="When user was archived", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="archived_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who archived this user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archived_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_archived",
            field=models.BooleanField(
                default=False, help_text="User is archived (soft deleted)"
            ),
        ),
    ]
