# Generated by Django 5.2.5 on 2025-11-28 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0036_alter_customuser_managers_customuser_archive_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gradesubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft (Auto-saved)"),
                    ("pending", "Pending Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("processing", "Processing"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="GradeSubmissionSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        help_text="Format: YYYY-YYYY (e.g., 2024-2025)", max_length=20
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("1st", "1st Semester"),
                            ("2nd", "2nd Semester"),
                            ("summer", "Summer"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "session_started_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the first grade was submitted",
                    ),
                ),
                (
                    "session_expires_at",
                    models.DateTimeField(help_text="2 hours after session start"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the session is still active"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When all subjects were submitted",
                        null=True,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-session_started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="gradesubmissionsession",
            index=models.Index(
                fields=["student", "is_active"], name="myapp_grade_student_2e08ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gradesubmissionsession",
            index=models.Index(
                fields=["session_expires_at"], name="myapp_grade_session_82f33b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="gradesubmissionsession",
            unique_together={("student", "academic_year", "semester")},
        ),
    ]
