# Generated by Django 5.2.5 on 2025-12-01 04:57

import myapp.models
import myapp.validators
from django.db import migrations, models


def check_table_exists(apps, schema_editor):
    """Check if EmailVerification table exists before attempting to delete it"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'myapp_emailverification'
            );
        """)
        return cursor.fetchone()[0]


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_alter_gradesubmission_status_gradesubmissionsession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=myapp.models.get_profile_storage, upload_to=myapp.models.profile_image_upload_path, validators=[myapp.validators.FileSizeValidator(max_size_mb=5, min_size_kb=1), myapp.validators.FileTypeValidator(allowed_category='image'), myapp.validators.ProfileImageValidator(max_size_mb=5), myapp.validators.MaliciousFileValidator()]),
        ),
        migrations.AlterField(
            model_name='documentsubmission',
            name='document_file',
            field=models.FileField(storage=myapp.models.get_document_storage, upload_to=myapp.models.document_upload_path, validators=[myapp.validators.FileSizeValidator(max_size_mb=10, min_size_kb=1), myapp.validators.FileTypeValidator(allowed_category='document'), myapp.validators.MaliciousFileValidator()]),
        ),
        migrations.AlterField(
            model_name='gradesubmission',
            name='grade_sheet',
            field=models.FileField(storage=myapp.models.get_grade_storage, upload_to=myapp.models.grade_upload_path, validators=[myapp.validators.FileSizeValidator(max_size_mb=10, min_size_kb=1), myapp.validators.FileTypeValidator(allowed_category='grade_sheet'), myapp.validators.MaliciousFileValidator()]),
        ),
        # Only delete EmailVerification table if it exists (skip for databases that never had it)
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS myapp_emailverification CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
