# Generated by Django 5.2.5 on 2025-12-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_customuser_profile_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
