@echo off
echo Starting PostgreSQL 17 Service...
echo.
echo Please wait...
powershell -Command "Start-Process powershell -Verb RunAs -ArgumentList '-ExecutionPolicy Bypass -File \"%~dp0start_postgresql17.ps1\"'"
