"""
Django settings for backend_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-FALLBACK-KEY-ONLY-FOR-DEVELOPMENT')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,192.168.100.13,*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'myapp',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'myapp', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite configuration (for development backup)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# PostgreSQL configuration
# Supports both POSTGRES_* (CI standard) and DB_* (local dev) environment variables
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('POSTGRES_DB', os.environ.get('DB_NAME', 'tcu_ceaa_database')),
        'USER': os.environ.get('POSTGRES_USER', os.environ.get('DB_USER', 'postgres')),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', os.environ.get('DB_PASSWORD', 'TCU@ADMIN!scholarship')),
        'HOST': os.environ.get('DATABASE_HOST', os.environ.get('DB_HOST', 'localhost')),
        'PORT': os.environ.get('DATABASE_PORT', os.environ.get('DB_PORT', '5432')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File Upload Settings (Security)
# Maximum upload size: 10MB (in bytes)
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10MB

# Maximum total request size (for forms with multiple files)
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Allowed content types (whitelist approach for security)
ALLOWED_UPLOAD_CONTENT_TYPES = [
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/jpg',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'myapp.CustomUser'

# Email Configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'TCU-CEAA Portal <noreply@tcu-ceaa.edu.ph>')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Email sending timeout (in seconds)
EMAIL_TIMEOUT = 30

# ============================================================================
# CLOUD STORAGE CONFIGURATION (Amazon S3)
# ============================================================================
USE_CLOUD_STORAGE = os.environ.get('USE_CLOUD_STORAGE', 'False') == 'True'

if USE_CLOUD_STORAGE:
    # AWS S3 Configuration
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'tcu-ceaa-documents')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '')
    AWS_S3_FILE_OVERWRITE = os.environ.get('AWS_S3_FILE_OVERWRITE', 'False') == 'True'
    AWS_DEFAULT_ACL = os.environ.get('AWS_DEFAULT_ACL', 'private')
    
    # Use S3 for media files
    DEFAULT_FILE_STORAGE = 'myapp.storage_backends.PrivateMediaStorage'
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/media/'

# ============================================================================
# ADVANCED OCR CONFIGURATION (AWS Textract)
# ============================================================================
USE_ADVANCED_OCR = os.environ.get('USE_ADVANCED_OCR', 'False') == 'True'
ADVANCED_OCR_REGION = os.environ.get('ADVANCED_OCR_REGION', 'us-east-1')
OCR_CONFIDENCE_THRESHOLD = int(os.environ.get('OCR_CONFIDENCE_THRESHOLD', '80'))

# ============================================================================
# AUTOMATED BIOMETRIC VERIFICATION CONFIGURATION
# ============================================================================
VERIFICATION_SERVICE_ENABLED = os.environ.get('VERIFICATION_SERVICE_ENABLED', 'False') == 'True'
VERIFICATION_SERVICE_REGION = os.environ.get('VERIFICATION_SERVICE_REGION', 'us-east-1')
VERIFICATION_SERVICE_ID = os.environ.get('VERIFICATION_SERVICE_ID', 'tcu-ceaa-verification')
VERIFICATION_SERVICE_MIN_CONFIDENCE = int(os.environ.get('VERIFICATION_SERVICE_MIN_CONFIDENCE', '80'))

# 🔒 SECURITY: AWS Cognito Identity Pool (for temporary credentials)
AWS_COGNITO_IDENTITY_POOL_ID = os.environ.get('AWS_COGNITO_IDENTITY_POOL_ID', 'us-east-1:a1252e7a-7da3-4703-88da-22cacd3b88b5')

# Face Verification Thresholds
FACE_SIMILARITY_THRESHOLD = float(os.environ.get('FACE_SIMILARITY_THRESHOLD', '0.99'))  # >99% for high confidence
FACE_CONFIDENCE_VERY_HIGH = float(os.environ.get('FACE_CONFIDENCE_VERY_HIGH', '0.99'))
FACE_CONFIDENCE_HIGH = float(os.environ.get('FACE_CONFIDENCE_HIGH', '0.95'))
FACE_CONFIDENCE_MEDIUM = float(os.environ.get('FACE_CONFIDENCE_MEDIUM', '0.90'))
FACE_CONFIDENCE_LOW = float(os.environ.get('FACE_CONFIDENCE_LOW', '0.85'))

# Verification Routing: Route verification attempts to admin if similarity below this threshold
VERIFICATION_ADMIN_REVIEW_THRESHOLD = float(os.environ.get('VERIFICATION_ADMIN_REVIEW_THRESHOLD', '0.90'))

# Cooldown Configuration
VERIFICATION_MAX_ATTEMPTS = int(os.environ.get('VERIFICATION_MAX_ATTEMPTS', '3'))
VERIFICATION_COOLDOWN_HOURS = int(os.environ.get('VERIFICATION_COOLDOWN_HOURS', '24'))

# ============================================================================
# SECURITY SETTINGS - Production Hardening
# ============================================================================

# 🔒 SECURITY: Production security headers
if not DEBUG:
    # Force HTTPS
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Content Security
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    
    # Proxy headers (if behind load balancer)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 🔒 SECURITY: Session configuration
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF protection
SESSION_COOKIE_AGE = 3600  # 1 hour session timeout

# 🔒 SECURITY: CSRF configuration
CSRF_COOKIE_HTTPONLY = False  # Must be False for frontend to read it
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False
CSRF_COOKIE_NAME = 'csrftoken'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3002",
    "http://127.0.0.1:3002",
    "http://localhost:3003",
    "http://127.0.0.1:3003",
]

# ⚠️ WARNING: CORS_ALLOW_ALL_ORIGINS should be False in production
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Only allow all origins in development
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# Test Runner Configuration
# Only discover tests in app directories (myapp/tests.py), not root backend/ directory
TEST_RUNNER = 'django.test.runner.DiscoverRunner'
TEST_DISCOVER_TOP_LEVEL = BASE_DIR
TEST_DISCOVER_ROOT = BASE_DIR
TEST_DISCOVER_PATTERN = 'test*.py'

# This prevents Django from discovering test_*.py files in the backend root directory
# Those are manual testing scripts, not Django test cases



